spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/summerpractice
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  springfox:
      documentation:
        swagger-ui:
          enabled: true